name: "Build Docs"
description: "build jekyll docs"
inputs:
  version:
    description: "Version number"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Npm cli install
      working-directory: ./docs
      run: npm ci
      shell: bash
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1.180.1
      with:
        ruby-version: "3.2" # Not needed with a .ruby-version file
        bundler-cache: false # runs 'bundle install' and caches installed gems automatically
        #cache-version: 0 # Increment this number if you need to re-download cached gems
        working-directory: "./docs"
    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5
    - name: Build with Jekyll
      working-directory: ./docs
      # Outputs to the './_site' directory by default
      shell: bash
      run: |
      	echo "=== Setting up environment for CI unit tests ===" && \
        curl -LO https://github.com/asdf-vm/asdf/releases/download/v0.18.0/asdf-v0.18.0-linux-amd64.tar.gz && \
        tar -xvzf asdf-v0.18.0-linux-amd64.tar.gz -C /usr/local/bin && \
        chmod +x /usr/local/bin/asdf && \
        pwd && \
        ls -la
        echo "from manual test tools versions file contains:"
        cat .tool-versions
        /usr/local/bin/asdf --version
        echo "Setting up asdf environment and adding plugins"
        export ASDF_DATA_DIR=$$HOME/.asdf && \
        export PATH=$$ASDF_DATA_DIR/shims:$$ASDF_DATA_DIR/bin:/usr/local/bin:$$PATH && \
        echo "Adding plugins from .tool-versions" && \
        while IFS=' ' read -r plugin version || [ -n "$$plugin" ]; do \
          plugin=$$(echo "$$plugin" | xargs); \
          first_char=$$(echo "$$plugin" | cut -c1); \
          if [ -n "$$plugin" ] && [ "$$first_char" != "#" ]; then \
            echo "Adding plugin: $$plugin (version: $$version)" && \
            /usr/local/bin/asdf plugin add "$$plugin" 2>&1 || echo "  -> Plugin $$plugin already added or failed"; \
          fi \
        done < .tool-versions && \
        echo "Listing available plugins:" && \
        /usr/local/bin/asdf plugin list && \
        echo "Installing asdf versions" && \
        /usr/local/bin/asdf install -v && \
        echo "Installed versions:" && \
        /usr/local/bin/asdf list && \
        echo "Node is at:" && \
        whereis node && \
        echo "Chosen one is at:" && \
        which node && \
        echo "Node version is:" && \
        node --version && \
        npm install && \
        echo "=== Finished installing dependencies ===" && \
        asdf info && \
        asdf current && \
        node --version && \
        npm --version && \
        make build BASE_URL="${{ steps.pages.outputs.base_path }}" VERSION="${{ inputs.version }}"

      #run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@v3
      with:
        path: "docs/_site/"
        name: jekyll-docs-${{ inputs.version }}
