name: "Perform static analysis"
description: "Perform static analysis"
inputs:
  sonar_organisation_key:
    description: "Sonar organisation key, used to identify the project"
    required: false
  sonar_project_key:
    description: "Sonar project key, used to identify the project"
    required: false
  sonar_token:
    description: "Sonar token, the API key"
    required: false
  # Note, conmpsite actions only support string inputs
  ignore_sonar_failure:
    description: "Whether to fail the build if the quality gate fails"
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: "Warn that ignore failure is enabled"
      if: ${{ fromJSON(inputs.ignore_sonar_failure) }}
      shell: bash
      run: |
        echo "WARNING: SonarQube failures will be ignored as per configuration."
        echo "::warning title=Stopping for Sonar failure is disabled:: SonarQube failures will be ignored as per configuration."
    - name: "Check prerequisites for performing static analysis"
      shell: bash
      id: check
      run: echo "secret_exist=${{ inputs.sonar_token != '' }}" >> $GITHUB_OUTPUT
    - name: "Perform static analysis"
      shell: bash
      if: steps.check.outputs.secret_exist == 'true'
      continue-on-error: ${{ fromJSON(inputs.ignore_sonar_failure) }}
      run: |
        export BRANCH_NAME=${GITHUB_HEAD_REF:-$(echo $GITHUB_REF | sed 's#refs/heads/##')}
        export SONAR_ORGANISATION_KEY=${{ inputs.sonar_organisation_key }}
        export SONAR_PROJECT_KEY=${{ inputs.sonar_project_key }}
        export SONAR_TOKEN=${{ inputs.sonar_token }}
        ./scripts/reports/perform-static-analysis.sh
