name: Acceptance tests
description: "Run acceptance tests for this repo"

inputs:
  testType:
    description: Type of test to run
    required: true
    default: main

  targetEnvironment:
    description: Name of the environment under test
    required: true
    default: main

  targetAccountGroup:
    description: Name of the account group under test
    default: nhs-notify-digital-letters-dev
    required: true

  targetComponent:
    description: Name of the component under test
    default: dl

runs:
  using: "composite"

  steps:
    - name: "Repo setup"
      shell: bash
      run: |
        npm ci

    - name: Run test - ${{ inputs.testType }}
      shell: bash
      run: |
        set -euo pipefail
        case "$TEST_TYPE" in
          main|integration|unit)
            make "test-$TEST_TYPE"
            ;;
          *)
            echo "Invalid testType: $TEST_TYPE" >&2
            exit 1
            ;;
        esac
      env:
        TEST_TYPE: ${{ inputs.testType }}
        ENVIRONMENT: ${{ inputs.targetEnvironment }}

    - name: Archive integration test results
      if: ${{ inputs.testType == 'integration' }}
      uses: actions/upload-artifact@v4
      with:
        name: Integration test report
        path: "tests/playwright/playwright-report"
