# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: NHS Notify Digital Letters
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Repository Template documentation for the NHS Notify Platform.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://nhsdigital.github.io" # the base hostname & protocol for your site, e.g. http://example.com

collections_dir: collections

collections:
  notify-repos:
    output: true
    sort_by: order
  diagrams:
    output: true
    sort_by: order
  events:
    output: true
    sort_by: order

just_the_docs:
  collections:
    events:
      name:  Events
      nav_exclude: false
      nav_fold: true
      search_exclude: false
    diagrams:
      name:  Diagrams
      nav_exclude: false
      nav_fold: true
      search_exclude: false
# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jemoji

#color_scheme: nhs
color_scheme: ce
# mermaid:
#   # Version of mermaid library
#   # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
#   version: "11.12.0"

aux_links:
  "NHS Notify Digital Letters on GitHub":
    - "//github.com/NHSDigital/nhs-notify-digital-letters"

aux_links_new_tab: false

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/NHSDigital/nhs-notify-digital-letters" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

nav_external_links:
  - title: Event Catalog
    url: ./eventcatalog
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

  - title: Notify Service Catalogue
    url: https://digital.nhs.uk/services/nhs-notify
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

  - title: Notify Tech Docs
    url: https://nhsdigital.github.io/nhs-notify/
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

  - title: NHS SEQF
    url: https://github.com/NHSDigital/software-engineering-quality-framework
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: false # set to true to open this link in a new tab - defaults to false

sass:
  quiet_deps: true

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Warning
    color: blue



defaults:


  - scope:
      path: "architecture"
      type: "pages"
    values:
      layout: "architecture"
      owner: NHS Notify
      author: NHS Notify
      last_modified_date: 2025-01-01

  - scope:
      path: "cloudevents"
    values:
      layout: "page"
      is_not_draft: false
      parent: Home
      owner: NHS Notify
      author: NHS Notify
      last_modified_date: 2025-01-01

  - scope:
      path: "schemas"
      type: "pages"
    values:
      layout: "page"
      is_not_draft: false
      parent: Home
      owner: NHS Notify
      author: NHS Notify
      last_modified_date: 2025-01-01

  - scope:
      path: ""
      type: "schema"
    values:
      layout: "page"
      is_not_draft: false
      owner: NHS Notify
      author: NHS Notify
      last_modified_date: 2025-01-01

  - scope:
      path: ""
      type: "diagrams"
    values:
      layout: "diagram"
      is_not_draft: false
      owner: NHS Notify
      author: NHS Notify
      last_modified_date: 2025-01-01
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
      owner: NHS Notify
      author: NHS Notify
      last_modified_date: 2025-01-01
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
include:
  - .version
  - version.json
  - _astro
  - _*.js


exclude:
  - package-lock.json
  - package.json
  - Makefile
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
